name: gas_sim_dbt
version: '1.0.0'
config-version: 2

profile: gas_sim

model-paths: ["models"]
test-paths:  ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  gas_sim_dbt:
    staging:
      +materialized: view
    features:
      +materialized: table
    marts:
      +materialized: table
